services:
  barber-shop-ui:
    build: .
    container_name: barber-shop-ui
    ports:
      - "5173:5173"    # keep for local dev & for the proxy target
    # … rest unchanged …
    networks: [barber-shop-network]

  caddy:
    image: caddy:2-alpine
    container_name: caddy
    depends_on:
      - barber-shop-ui
    ports:
      - "80:80"        
      - "5173:5173"    
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
    networks: [barber-shop-network]

networks:
  barber-shop-network:
    external: true
