services:
  barber-shop-ui:
    build: .
    container_name: barber-shop-ui
    ports:
      - "80:5173"
    working_dir: /app
    volumes:
      - ./:/app            
      - /app/node_modules  
    env_file:
      - .env    
    networks:
      - barber-shop-network

networks:
  barber-shop-network:
    external: true
