services:
  barber-shop-ui:
    build: .
    container_name: barber-shop-ui
    working_dir: /app
    networks: [barber-shop-network]

    volumes:
      - ./:/app              
      - /app/node_modules     

    # frontend env vars
    env_file:
      - .env

  caddy:
    image: caddy:2-alpine
    container_name: caddy
    depends_on:
      - barber-shop-ui
    ports:
      - "80:80"               # public port
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
    networks: [barber-shop-network]

networks:
  barber-shop-network:
    external: true
